# Generated by Django 3.1.1 on 2021-01-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210112_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.PositiveIntegerField(),
        ),
    ]
